export const KEYBOARD_SEEK_SECONDS = 5
export const SNAP_ENTER_THRESHOLD_PIXELS = 8
export const SNAP_RELEASE_THRESHOLD_PIXELS = 14
export const SNAP_SWITCH_MARGIN_PIXELS = 2
export const TIMELINE_ITEM_MIN_WIDTH_PIXELS = 4
export const TIMELINE_RULER_TARGET_TICK_SPACING_PIXELS = 92
